name: 'Update JDKs'
description: 'Update .teamcity/jdks.yaml with the latest JDK versions'
author: 'Gradle Inc.'

inputs:
  token:
    required: true
    description: 'The GitHub authentication token'
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
